# Site settings | 网站设置
title: xiaoyulejia
SEOTitle: 小娱乐家的博客 | xiaoyulejia
header-img: img/home-bg-he.jpg
email: yihanchenadma@gmail.com
description: "xiaoyulejia的博客"
keyword: "xiaoyulejia, xiaoyulejia的博客, xiaoyulejia, xiaoyulejia, xiaoyulejia's blog"
url: "http://xiaoyulejia.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xiaoyulejia/xiaoyulejia.github.io" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "你是二十七度飘落的雪，是席卷阿卡迪亚湾的风暴，是我生命中难得一见的日食。"
sidebar-avatar: /img/head.jpg      # 头像





# SNS settings | 社交网络设置
#facebook_username: rainbom.z
github_username: xiaoyulejia
#zhihu_username: RainbomSea
#csdn_username: qq_39268193




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: cd17038db161edb68862                          #生成的clientID
  clientSecret: 3ababc413d47f4cf6f9482e00806a6651cca1542    #生成的clientSecret
  repo: xiaoyulejia.github.io    #仓库名称
  owner: xiaoyulejia    # github用户名
  admin: xiaoyulejia
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 3fc1e0f9bb44b66f8af2db1bd8090b1b


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "GitHub·xiaoyulejia",
        href: "https://github.com/xiaoyulejia"
    },{
        title: "Bilibili·唧唧唧啾啾",
        href: "https://space.bilibili.com/504877841/dynamic"
    }
]
